name: notary_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_tawk: ^0.1.0
  url_launcher: ^6.0.6


dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

# flutter: 
#   uses-material-design: true
#   # assets:
#   #   - img/logo.jpg

flutter:
  uses-material-design: true
  assets:
    - img/profile.png
    - img/map.JPG
